# Generated by Django 4.0.5 on 2022-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ge', models.CharField(default='ბლოგი', max_length=255)),
                ('question_en', models.CharField(default='Blog', max_length=255)),
                ('answer_ge', models.TextField(default='მოკლე ტექსტი', max_length=1000)),
                ('answer_en', models.TextField(default='Short Text', max_length=1000)),
            ],
        ),
    ]
