# Generated by Django 4.0.5 on 2022-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_type',
            field=models.CharField(default='material', max_length=20),
        ),
    ]
