# Generated by Django 4.0.5 on 2022-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ge', models.CharField(default='ბლოგი', max_length=255)),
                ('title_en', models.CharField(default='Blog', max_length=255)),
                ('short_text_ge', models.TextField(default='მოკლე ტექსტი', max_length=1000)),
                ('short_text_en', models.TextField(default='Short Text', max_length=1000)),
                ('long_text_ge', models.TextField(default='გრძელი ტექსტი', max_length=10000)),
                ('long_text_en', models.TextField(default='Long Text', max_length=10000)),
                ('image', models.ImageField(default='media/default-product.jpeg', null=True, upload_to='images/')),
            ],
        ),
    ]
